name: Publish Development NuGet package

on:
  workflow_dispatch:
  push:
    branches: [ "development" ]
    paths-ignore:
    - 'README.md'
    - '/github/**/*.*'

jobs:
  build:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "~/.dotnet"
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore

    - name: Test
      working-directory: ./src
      run: dotnet test -c Release

    - name: Install CycloneDX tool
      run: export PATH="$PATH:/home/actions-runner/.dotnet/tools" && dotnet tool install --global CycloneDX

    - name: Generate SBOM file
      working-directory: ./src
      run: export PATH="$PATH:/home/actions-runner/.dotnet/tools" && dotnet CycloneDX ./SolidCode.Extensions.Configuration.Yaml.sln

    - name: Upload SBOM file to Dependency Track server
      working-directory: ./src
      env:
        DEPENDENCY_TRACK_API_KEY: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
        DEPENDENCY_TRACK_URL: ${{ secrets.DEPENDENCY_TRACK_URL }}
        DEPENDENCY_TRACK_PROJECT_GUID: ${{ secrets.DEPENDENCY_TRACK_PROJECT_GUID_DEVELOPMENT }}
      run: |
        curl -X POST "$DEPENDENCY_TRACK_URL/api/v1/bom" \
        -H "Content-Type: multipart/form-data" \
        -H "X-Api-Key: $DEPENDENCY_TRACK_API_KEY" \
        -F "project=$(DEPENDENCY_TRACK_PROJECT_GUID)" \
        -F "bom=@bom.xml"

    - name: Pack
      working-directory: ./src/SolidCode.Extensions.Configuration.Yaml
      run: dotnet pack --configuration Release

    - name: Publish
      working-directory: ./src/SolidCode.Extensions.Configuration.Yaml
      run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.MYGET_ORG_API_KEY }} --source https://www.myget.org/F/solidcode/api/v2/package
