name: Run tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "release", "development" ]
    paths-ignore:
    - 'README.md'

jobs:
  build:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "~/.dotnet"
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore

    - name: Test
      working-directory: ./src
      run: dotnet test -c Release
