<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<LangVersion>14.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>

		<EnableNETAnalyzers>True</EnableNETAnalyzers>
		<AnalysisLevel>10.0-recommended</AnalysisLevel>

		<Copyright>©️ 2024-2025 Andrey Veselov</Copyright>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="xunit.v3" Version="3.2.1" />
		<PackageReference Include="xunit.analyzers" Version="1.26.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SolidCode.Extensions.Configuration.Yaml\SolidCode.Extensions.Configuration.Yaml.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Bugfix.FirstLineIsEmpty.yaml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="config.yaml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>